_reference_jdk: &reference_jdk
  JDK="adopt@1.8"

_reference_build: &reference_build
  os: linux
  env: *reference_jdk

os:
  - osx
  - linux
  - windows

git:
  depth: false
  autocrlf: input

language: shell
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - secure: "Huc1orMmBXQxQ8Z7zsn9bg3cPS++QQepRz1EtXSyYBx/F0x5P9bjm1iu4+NuXSD+t2dAMjvkfblNtBWd5rpco2SYPNHNd0ejgBzEHi+OnQ61/4NXdUXATSfEg9V1fcroyYrdl6ccjFN+/bTp4wxRiurMxa663+Tv4BPGCTQ/sdus3SHzILDMWlV9nbue88kSunGv6aBOkiSGfa4YdfxTlisyyGWJfxptpThBn69POpNPfaFTvymgVQgRtMLJZM2xIY8okSeS413RjBwww6DGarKr0wP02tKsBswnw4oyCINVhBUeK9RJowLahcOWk4GZXbalRoNs0hAwaod1PAVrufna5PwXBTOXZqKNVEI1ta1Fr9FkQP6oj+3Wife5IEggLxTtoheKIcUv/5tn1Ex5YJOMwkze79+rN01YqmV4R/jlDxB4J4jCQDQlfGttAzUzyLYcS5t9MuVcopkRJtCqASbszq7RxG2DxKDXS+ENRDR+WIBj1LfDfkl0j1V1J59Iu4hRcEyEbox6ZtOegfAW0wBzlDFVanQK1RMnocbkI5uHLTY3IXf7uvqSjOMJ8fB9Slxas4tLyGjjylLve3ftmd11hH4uDUuuMjMqEikoXWli7zmIr2SCGImDthxCWCIwRSBPNNcHzGNnCdwR+EhdE2HOIWFwxR8+tp1K15EVR2A="
    - secure: "eGXNMD0SsUUKHUzh5D2eZWW2G9m9I/E6ophav3N+fZ8EUmJyeh78pzbsHFYqAoitfz9tEVM3SL8x5VG7X6QJcLywnxBMrhZxiFNYr3oOFqH44IvTSm91MX7itwCftEDfW0rwSZMzjzm76eknALB/2/+HBKqm/sGz6Vj86oIpBReb7RuRAZrsF+QK8wU7HYNBweqjGnjMNyu+hx5HSotcAd79nDTrAU+8jC2lknEqSLcyIljKH/IoMfDhG1pmwJd1aWmWo8Ja4INE6HovdAUaZTd9vhxFVQLFS7B19WBQZOZSjWz+6+xufgZxF0WLZdWSYwa1Bd0VmKDP+3nS7dbQKsnS+995OLDLqr8pflXBKqTz3hatZSObovWqwftxprlWl4ykLE/Nw/NtHmpE7GA5/2a+Z8bgkoCzPG+AubXkH1933QqEr29LYMgiQJOq+sdbLUDVHyWguAP3Vp6w0AHwjRAAHU2+cWYOOZh1+4QHwsN3Zur5GFjkdF+L/8sv5TXaFuoiGTaoRE75PDjKeHGfIk1xeD4hcH5L2MmEP2Aw4bvPFZOKH99efqIkD5zZ3GQglsJksIgN7CxOn71lPEqmBMrfxhP6MjuPzcpeiVjT0kMw7q4fi+FTesR9K8NxLX/GdInBb8svtNabzFCixWjsyS1u4/aZwJB9ctu78OzUoe4="
    - secure: "LCUewl+3Qndqu08B6QRPuor80EmhXGTELnXv38Kkb1XB7pqXZmvWRuwvHFjID7BkK09wILsD++QXlHnjZcj/d2zgN7a564GTzlpT7pSh3RzXqiOMJd2sddeKyV2Yx+IPamft1NSV+0A+1C8gXnDUYs3yg8ZHcApXRvuCIPI72Q1nlQAlSJORm6Ds+63TufLobMOJaX4aFwB0SAcH1adWMi+3dIdv800LsXL991mvmmJkIu3Uk868p+1ps4kMckv6Tw3j/zgJcQv7x/VpEIiPtQp4AzRVLNmKRj6KFMHnRZwpGn+mlCmGIaVpba5Ju9Ehhd9waziIGMPvOIIYgPfDRgVi0EEy4lBbNNqVZNf7uRGfv+1XHKIl5RlIByiSqgZJGMWCt/qSmbfktetGuxK+jwS9ktY5K6vkUNCh3fJNb+39MKbZgXNz6XSxpU0Gr02snX8jGsMi604Q/VTFdeWmyRH36Zz2w0AXX0LXDcEcSpAH+acW0fhEuIAe8QOfYGkDhoQ5Fmr/42h/H1kB5v2CLCIx/brFtXEQuhqpWR/U0IH+SxrytmxxaYCo+UPCSCF2CBZXOWk1l/pgRTgfftBnd4BVv1NEFz4EsrziuiBEY1uVt7yZPv2CYA1bPec67t+zFJUZN8obXB5FRH9mK+h6HXmYL2KoMTLkwIiGSSIv+po="
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@"
    - JDK="adopt-openj9"

stages:
  - base
  - test
  - name: deploy
    if: type != pull_request AND repo = DanySK/upgradle

jobs:
  exclude:
    - <<: *reference_build
      stage: test
  include:
    - <<: *reference_build
      stage: base
      after_success: bash <(curl -s https://codecov.io/bash)
      script:
        - travis_retry ./gradlew clean check jacocoTestReport
    - <<: *reference_build
      stage: deploy
      install:
        - openssl aes-256-cbc -K $encrypted_f6fa8cf5bc89_key -iv $encrypted_f6fa8cf5bc89_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
        - bash prepare_environment.sh
        - rm prepare_environment.sh
      script: travis_retry ./gradlew publish

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - travis_retry ./gradlew clean check
after_failure:
  - dig +short myip.opendns.com @resolver1.opendns.com
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
