os:
   - linux
   - osx
dist: xenial
git:
  depth: false
language: java
env:
  global:
    - secure: "Huc1orMmBXQxQ8Z7zsn9bg3cPS++QQepRz1EtXSyYBx/F0x5P9bjm1iu4+NuXSD+t2dAMjvkfblNtBWd5rpco2SYPNHNd0ejgBzEHi+OnQ61/4NXdUXATSfEg9V1fcroyYrdl6ccjFN+/bTp4wxRiurMxa663+Tv4BPGCTQ/sdus3SHzILDMWlV9nbue88kSunGv6aBOkiSGfa4YdfxTlisyyGWJfxptpThBn69POpNPfaFTvymgVQgRtMLJZM2xIY8okSeS413RjBwww6DGarKr0wP02tKsBswnw4oyCINVhBUeK9RJowLahcOWk4GZXbalRoNs0hAwaod1PAVrufna5PwXBTOXZqKNVEI1ta1Fr9FkQP6oj+3Wife5IEggLxTtoheKIcUv/5tn1Ex5YJOMwkze79+rN01YqmV4R/jlDxB4J4jCQDQlfGttAzUzyLYcS5t9MuVcopkRJtCqASbszq7RxG2DxKDXS+ENRDR+WIBj1LfDfkl0j1V1J59Iu4hRcEyEbox6ZtOegfAW0wBzlDFVanQK1RMnocbkI5uHLTY3IXf7uvqSjOMJ8fB9Slxas4tLyGjjylLve3ftmd11hH4uDUuuMjMqEikoXWli7zmIr2SCGImDthxCWCIwRSBPNNcHzGNnCdwR+EhdE2HOIWFwxR8+tp1K15EVR2A="
    - secure: "eGXNMD0SsUUKHUzh5D2eZWW2G9m9I/E6ophav3N+fZ8EUmJyeh78pzbsHFYqAoitfz9tEVM3SL8x5VG7X6QJcLywnxBMrhZxiFNYr3oOFqH44IvTSm91MX7itwCftEDfW0rwSZMzjzm76eknALB/2/+HBKqm/sGz6Vj86oIpBReb7RuRAZrsF+QK8wU7HYNBweqjGnjMNyu+hx5HSotcAd79nDTrAU+8jC2lknEqSLcyIljKH/IoMfDhG1pmwJd1aWmWo8Ja4INE6HovdAUaZTd9vhxFVQLFS7B19WBQZOZSjWz+6+xufgZxF0WLZdWSYwa1Bd0VmKDP+3nS7dbQKsnS+995OLDLqr8pflXBKqTz3hatZSObovWqwftxprlWl4ykLE/Nw/NtHmpE7GA5/2a+Z8bgkoCzPG+AubXkH1933QqEr29LYMgiQJOq+sdbLUDVHyWguAP3Vp6w0AHwjRAAHU2+cWYOOZh1+4QHwsN3Zur5GFjkdF+L/8sv5TXaFuoiGTaoRE75PDjKeHGfIk1xeD4hcH5L2MmEP2Aw4bvPFZOKH99efqIkD5zZ3GQglsJksIgN7CxOn71lPEqmBMrfxhP6MjuPzcpeiVjT0kMw7q4fi+FTesR9K8NxLX/GdInBb8svtNabzFCixWjsyS1u4/aZwJB9ctu78OzUoe4="
    - secure: "LCUewl+3Qndqu08B6QRPuor80EmhXGTELnXv38Kkb1XB7pqXZmvWRuwvHFjID7BkK09wILsD++QXlHnjZcj/d2zgN7a564GTzlpT7pSh3RzXqiOMJd2sddeKyV2Yx+IPamft1NSV+0A+1C8gXnDUYs3yg8ZHcApXRvuCIPI72Q1nlQAlSJORm6Ds+63TufLobMOJaX4aFwB0SAcH1adWMi+3dIdv800LsXL991mvmmJkIu3Uk868p+1ps4kMckv6Tw3j/zgJcQv7x/VpEIiPtQp4AzRVLNmKRj6KFMHnRZwpGn+mlCmGIaVpba5Ju9Ehhd9waziIGMPvOIIYgPfDRgVi0EEy4lBbNNqVZNf7uRGfv+1XHKIl5RlIByiSqgZJGMWCt/qSmbfktetGuxK+jwS9ktY5K6vkUNCh3fJNb+39MKbZgXNz6XSxpU0Gr02snX8jGsMi604Q/VTFdeWmyRH36Zz2w0AXX0LXDcEcSpAH+acW0fhEuIAe8QOfYGkDhoQ5Fmr/42h/H1kB5v2CLCIx/brFtXEQuhqpWR/U0IH+SxrytmxxaYCo+UPCSCF2CBZXOWk1l/pgRTgfftBnd4BVv1NEFz4EsrziuiBEY1uVt7yZPv2CYA1bPec67t+zFJUZN8obXB5FRH9mK+h6HXmYL2KoMTLkwIiGSSIv+po="

matrix:
  include:
    - jdk: openjdk8
      env: PUBLISH="true"
    - jdk: openjdk9
      env: PUBLISH="false"
    - jdk: openjdk10
      env: PUBLISH="false"
    - jdk: openjdk11
      env: PUBLISH="false"
    - jdk: openjdk12
      env: PUBLISH="false"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  - export SHOULD_CONFIGURE="$(if ! $TRAVIS_PULL_REQUEST && [ $TRAVIS_REPO_SLUG = "DanySK/boilerplate" ]; then echo "true"; else echo "false"; fi)"

install: >-
    if $SHOULD_CONFIGURE; then
        openssl aes-256-cbc -K $encrypted_f6fa8cf5bc89_key -iv $encrypted_f6fa8cf5bc89_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
        bash prepare_environment.sh
    fi

script: ./gradlew clean check sourcesJar javadocJar

after_success: if $SHOULD_CONFIGURE && $PUBLISH; then ./gradlew publish publish; fi
